/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package eagleeye;

import com.github.sarxos.webcam.Webcam;
import com.github.sarxos.webcam.WebcamPanel;
import com.github.sarxos.webcam.WebcamResolution;
import static eagleeye.EagleEye.ee;
import java.awt.Image;
import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;
import javax.swing.JOptionPane;
import static javax.swing.JOptionPane.QUESTION_MESSAGE;
import static javax.swing.JOptionPane.YES_NO_OPTION;

/**
 *
 * @author aftab
 */
public class CameraPage extends javax.swing.JFrame {

    WebcamPanel myCameraPanel ;
    static Webcam myCam;
    private Image image = null;
    
    public CameraPage() {
        initComponents();
        
       
        myCam = Webcam.getDefault();
        
        myCam.setViewSize(WebcamResolution.VGA.getSize());
        
        myCameraPanel = new WebcamPanel(myCam);
        myCameraPanel.setImageSizeDisplayed(false);
        myCameraPanel.setSize(660, 480);
        myCameraPanel.setFPSDisplayed(true);
        myCameraPanel.setDisplayDebugInfo(true);
        myCameraPanel.setImageSizeDisplayed(true);
        
        this.FrameCameraPanel.add(this.myCameraPanel);
        
        revalidate();
        repaint();
        this.setVisible(true);
    }

    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        CameraPageMainPanel = new javax.swing.JPanel();
        FrameCameraPanel = new javax.swing.JPanel();
        imageLabel = new javax.swing.JLabel();
        takePicButton = new javax.swing.JButton();
        cancelButton = new javax.swing.JButton();

        jLabel1.setText("jLabel1");

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        setTitle("Take User Image");
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });

        CameraPageMainPanel.setBackground(new java.awt.Color(0, 0, 0));

        imageLabel.setBackground(new java.awt.Color(0, 0, 0));
        imageLabel.setIcon(new javax.swing.ImageIcon("E:\\EagleEye\\R\\home.png"));

        javax.swing.GroupLayout FrameCameraPanelLayout = new javax.swing.GroupLayout(FrameCameraPanel);
        FrameCameraPanel.setLayout(FrameCameraPanelLayout);
        FrameCameraPanelLayout.setHorizontalGroup(
            FrameCameraPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(imageLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        FrameCameraPanelLayout.setVerticalGroup(
            FrameCameraPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(imageLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 480, Short.MAX_VALUE)
        );

        takePicButton.setText("Take Pic");
        takePicButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                takePicButtonActionPerformed(evt);
            }
        });

        cancelButton.setText("Cancel");
        cancelButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout CameraPageMainPanelLayout = new javax.swing.GroupLayout(CameraPageMainPanel);
        CameraPageMainPanel.setLayout(CameraPageMainPanelLayout);
        CameraPageMainPanelLayout.setHorizontalGroup(
            CameraPageMainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(CameraPageMainPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(FrameCameraPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(CameraPageMainPanelLayout.createSequentialGroup()
                .addGap(266, 266, 266)
                .addComponent(takePicButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(cancelButton)
                .addContainerGap(238, Short.MAX_VALUE))
        );
        CameraPageMainPanelLayout.setVerticalGroup(
            CameraPageMainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(CameraPageMainPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(FrameCameraPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(CameraPageMainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(takePicButton)
                    .addComponent(cancelButton))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(CameraPageMainPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(CameraPageMainPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void takePicButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_takePicButtonActionPerformed
        image = myCam.getImage();
        ee.sup.setUserImage(image);
        this.myCam.close();
        ee.sup.isImageTaken=true;
        ee.sup.setEnabled(true);
        this.dispose();
    }//GEN-LAST:event_takePicButtonActionPerformed

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        int c = JOptionPane.showConfirmDialog(this, "Are You Sure to Exit Without taking Image?","EXIT?",YES_NO_OPTION);
        if( c == 0 )
        {
             this.myCam.close();
             this.dispose();
             ee.sup.setEnabled(true);
        }
    }//GEN-LAST:event_formWindowClosing

    private void cancelButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelButtonActionPerformed
        int c = JOptionPane.showConfirmDialog(this, "Are You Sure to Exit Without taking Image?","EXIT?",YES_NO_OPTION);
        if( c == 0 )
        {
             this.myCam.close();
             this.dispose();
             ee.sup.setEnabled(true);
        }
    }//GEN-LAST:event_cancelButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CameraPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CameraPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CameraPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CameraPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CameraPage().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel CameraPageMainPanel;
    private javax.swing.JPanel FrameCameraPanel;
    private javax.swing.JButton cancelButton;
    private javax.swing.JLabel imageLabel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JButton takePicButton;
    // End of variables declaration//GEN-END:variables
}
