/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package eagleeye;

import static eagleeye.EagleEye.ee;
import java.awt.Color;
import java.awt.Graphics;
import java.awt.Image;
import java.io.File;
import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.imageio.ImageIO;
import javax.swing.Icon;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import static javax.swing.JOptionPane.INFORMATION_MESSAGE;

/**
 *
 * @author aftab
 */
public class FirstPage extends javax.swing.JFrame {

    /**
     * Creates new form FirstPage
     */
    Image bkPic;
    ImageIcon bkPicIcon;
    
    private boolean supReLoaded = false;
    
    public FirstPage() {
        initComponents();
        this.setLocationRelativeTo(null);
        try {
            bkPic = ImageIO.read(new File("E://EagleEye//R//main.jpeg"));
            bkPicIcon = new ImageIcon(bkPic.getScaledInstance(805, 645, 0));
        } catch (IOException ex) {
            Logger.getLogger(FirstPage.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        revalidate();
        repaint();
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        FirstPageMainPanel = new javax.swing.JPanel()
        {
            protected void paintComponent(Graphics g)
            {
                g.drawImage(bkPicIcon.getImage(),0,0,null);
                super.paintComponent(g);
            }
        }
        ;
        logo = new javax.swing.JLabel();
        signUpButton = new javax.swing.JButton();
        signInButton = new javax.swing.JButton();
        AftabKhalil = new javax.swing.JLabel();
        DeviceConnected = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        setTitle("Eagle Eye ...");
        setBackground(new java.awt.Color(0, 0, 0));
        setForeground(java.awt.Color.black);
        setResizable(false);
        setSize(new java.awt.Dimension(800, 640));
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                FirstPageClosing(evt);
            }
        });

        FirstPageMainPanel.setOpaque(false);
        FirstPageMainPanel.setBackground(new java.awt.Color(0, 0, 0));

        logo.setIcon(new javax.swing.ImageIcon("E:\\EagleEye\\R\\logo.png")); // NOI18N
        logo.setText("AftabKhalil");

        signUpButton.setText("Sign Up");
        signUpButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                signUpButtonActionPerformed(evt);
            }
        });

        signInButton.setText("Sign In");
        signInButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                signInButtonActionPerformed(evt);
            }
        });

        AftabKhalil.setForeground(new java.awt.Color(255, 255, 255));
        AftabKhalil.setText("Made By: Aftab Khalil, B14158002");

        DeviceConnected.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout DeviceConnectedLayout = new javax.swing.GroupLayout(DeviceConnected);
        DeviceConnected.setLayout(DeviceConnectedLayout);
        DeviceConnectedLayout.setHorizontalGroup(
            DeviceConnectedLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 20, Short.MAX_VALUE)
        );
        DeviceConnectedLayout.setVerticalGroup(
            DeviceConnectedLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 20, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout FirstPageMainPanelLayout = new javax.swing.GroupLayout(FirstPageMainPanel);
        FirstPageMainPanel.setLayout(FirstPageMainPanelLayout);
        FirstPageMainPanelLayout.setHorizontalGroup(
            FirstPageMainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(FirstPageMainPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(FirstPageMainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, FirstPageMainPanelLayout.createSequentialGroup()
                        .addGap(0, 476, Short.MAX_VALUE)
                        .addGroup(FirstPageMainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(FirstPageMainPanelLayout.createSequentialGroup()
                                .addComponent(signUpButton, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(signInButton, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(logo, javax.swing.GroupLayout.PREFERRED_SIZE, 228, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(86, 86, 86))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, FirstPageMainPanelLayout.createSequentialGroup()
                        .addComponent(DeviceConnected, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(AftabKhalil)
                        .addContainerGap())))
        );
        FirstPageMainPanelLayout.setVerticalGroup(
            FirstPageMainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, FirstPageMainPanelLayout.createSequentialGroup()
                .addGap(198, 198, 198)
                .addComponent(logo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(FirstPageMainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(signUpButton)
                    .addComponent(signInButton))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 301, Short.MAX_VALUE)
                .addGroup(FirstPageMainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(AftabKhalil)
                    .addComponent(DeviceConnected, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(15, 15, 15))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(FirstPageMainPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(FirstPageMainPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void FirstPageClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_FirstPageClosing
        ee.fp.setEnabled(false);
        JOptionPane.showMessageDialog(null,"The qpplication will continue to work in the background.","I am not closing!",INFORMATION_MESSAGE);
        ee.fp.setVisible(false);
        ee.mf.setEnabled(true);
    }//GEN-LAST:event_FirstPageClosing

    private void signInButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_signInButtonActionPerformed
        if(ee.sipReloaded == false)
        {
             ee.sipReloaded = true;
             ee.sip.setVisible(true);
             ee.fp.setVisible(false);
        }
        else
        {
             ee.sip.dispose();
             ee.sip = new SighnInPage();
             if(ee.deviceConnected==true)
            {
                ee.sip.DeviceConnected.setBackground(Color.green);
            }
            else
            {
                ee.sip.DeviceConnected.setBackground(Color.red);
            }
            ee.sup.revalidate();
            ee.sup.repaint();
             ee.sip.setVisible(true);
             ee.fp.setVisible(false);
        }
    }//GEN-LAST:event_signInButtonActionPerformed

    private void signUpButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_signUpButtonActionPerformed
        if(supReLoaded == false)
        {
             supReLoaded = true;
             ee.sup.setVisible(true);
             ee.fp.setVisible(false);
        }
        else
        {
            ee.sup.dispose();
            ee.sup = new SignUpPage();
            if(ee.deviceConnected==true)
            {
                ee.sup.DeviceConnected.setBackground(Color.green);
            }
            else
            {
                ee.sup.DeviceConnected.setBackground(Color.red);
            }
            ee.sup.revalidate();
            ee.sup.repaint();
            ee.sup.setVisible(true);
            ee.fp.setVisible(false);
        }
    }//GEN-LAST:event_signUpButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FirstPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FirstPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FirstPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FirstPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FirstPage().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel AftabKhalil;
    public javax.swing.JPanel DeviceConnected;
    private javax.swing.JPanel FirstPageMainPanel;
    private javax.swing.JLabel logo;
    private javax.swing.JButton signInButton;
    private javax.swing.JButton signUpButton;
    // End of variables declaration//GEN-END:variables
}
