/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package eagleeye;

import static eagleeye.EagleEye.ee;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import static javax.swing.JOptionPane.ERROR_MESSAGE;
import static javax.swing.JOptionPane.INFORMATION_MESSAGE;

/**
 *
 * @author aftab
 */
 public class SighnInPage extends javax.swing.JFrame
{
     private String userIdInput;
     private String passwordInput;
    
    /**
     * Creates new form SighnInPage
     */
    public SighnInPage() {
        initComponents();
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        signInPageMainPanel = new javax.swing.JPanel();
        userIdField = new javax.swing.JTextField();
        userIdLabel = new javax.swing.JLabel();
        passwordLabel = new javax.swing.JLabel();
        logoLabel = new javax.swing.JLabel();
        signInButton = new javax.swing.JButton();
        backButton = new javax.swing.JButton();
        passwordField = new javax.swing.JPasswordField();
        AftabKhalil = new javax.swing.JLabel();
        DeviceConnected = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        setTitle("Eagle Eye ...");
        setBackground(new java.awt.Color(0, 0, 0));
        setResizable(false);
        setSize(new java.awt.Dimension(800, 640));
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                SignInPageClosing(evt);
            }
        });

        signInPageMainPanel.setBackground(new java.awt.Color(0, 0, 0));
        signInPageMainPanel.setForeground(new java.awt.Color(255, 255, 255));

        userIdField.setFont(new java.awt.Font("MV Boli", 1, 14)); // NOI18N
        userIdField.setMargin(new java.awt.Insets(0, 2, 0, 2));

        userIdLabel.setFont(new java.awt.Font("MV Boli", 1, 14)); // NOI18N
        userIdLabel.setForeground(new java.awt.Color(255, 255, 255));
        userIdLabel.setText("User Id:");

        passwordLabel.setFont(new java.awt.Font("MV Boli", 1, 14)); // NOI18N
        passwordLabel.setForeground(new java.awt.Color(255, 255, 255));
        passwordLabel.setText("Password:");

        logoLabel.setIcon(new javax.swing.ImageIcon("E:\\EagleEye\\R\\logoPic.png")); // NOI18N

        signInButton.setText("Sign In");
        signInButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                signInButtonActionPerformed(evt);
            }
        });

        backButton.setText("< Back");
        backButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backButtonActionPerformed(evt);
            }
        });

        passwordField.setFont(new java.awt.Font("Arial Black", 1, 14)); // NOI18N

        AftabKhalil.setForeground(new java.awt.Color(255, 255, 255));
        AftabKhalil.setText("Made By: Aftab Khalil, B14158002");

        DeviceConnected.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout DeviceConnectedLayout = new javax.swing.GroupLayout(DeviceConnected);
        DeviceConnected.setLayout(DeviceConnectedLayout);
        DeviceConnectedLayout.setHorizontalGroup(
            DeviceConnectedLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 20, Short.MAX_VALUE)
        );
        DeviceConnectedLayout.setVerticalGroup(
            DeviceConnectedLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 20, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout signInPageMainPanelLayout = new javax.swing.GroupLayout(signInPageMainPanel);
        signInPageMainPanel.setLayout(signInPageMainPanelLayout);
        signInPageMainPanelLayout.setHorizontalGroup(
            signInPageMainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(signInPageMainPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(DeviceConnected, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30)
                .addGroup(signInPageMainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, signInPageMainPanelLayout.createSequentialGroup()
                        .addComponent(logoLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 85, Short.MAX_VALUE)
                        .addGroup(signInPageMainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(signInPageMainPanelLayout.createSequentialGroup()
                                .addGroup(signInPageMainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(passwordLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 85, Short.MAX_VALUE)
                                    .addComponent(userIdLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(signInPageMainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(passwordField, javax.swing.GroupLayout.DEFAULT_SIZE, 150, Short.MAX_VALUE)
                                    .addComponent(userIdField)))
                            .addGroup(signInPageMainPanelLayout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addComponent(backButton, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(signInButton, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(110, 110, 110))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, signInPageMainPanelLayout.createSequentialGroup()
                        .addComponent(AftabKhalil, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())))
        );
        signInPageMainPanelLayout.setVerticalGroup(
            signInPageMainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, signInPageMainPanelLayout.createSequentialGroup()
                .addGroup(signInPageMainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(signInPageMainPanelLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(DeviceConnected, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(signInPageMainPanelLayout.createSequentialGroup()
                        .addGroup(signInPageMainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(signInPageMainPanelLayout.createSequentialGroup()
                                .addGap(130, 130, 130)
                                .addGroup(signInPageMainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(userIdLabel)
                                    .addComponent(userIdField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(19, 19, 19)
                                .addGroup(signInPageMainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(passwordLabel)
                                    .addComponent(passwordField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(34, 34, 34)
                                .addGroup(signInPageMainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(signInButton)
                                    .addComponent(backButton)))
                            .addGroup(signInPageMainPanelLayout.createSequentialGroup()
                                .addGap(45, 45, 45)
                                .addComponent(logoLabel)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 275, Short.MAX_VALUE)
                        .addComponent(AftabKhalil)))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(signInPageMainPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 11, Short.MAX_VALUE)
                .addComponent(signInPageMainPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void SignInPageClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_SignInPageClosing
        System.exit(0);
        ee.sip.setEnabled(false);
        JOptionPane.showMessageDialog(null,"The qpplication will continue to work in the background.","I am not closing!",INFORMATION_MESSAGE);
        ee.sip.setVisible(false);
        ee.sip.setEnabled(true);
        ee.mf.setEnabled(true);
    }//GEN-LAST:event_SignInPageClosing

    private void signInButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_signInButtonActionPerformed
        ee.lp.setUser(userIdInput);
        ee.lp.setVisible(true);
        ee.sip.setVisible(false);
        return;
        
        /*userIdInput = userIdField.getText();
        passwordInput = passwordField.getText();
        
        if(userIdInput.equals(""))
        {
            JOptionPane.showMessageDialog(this,"Please Write UserId","UserId?",ERROR_MESSAGE);
            return;
        }
        if(passwordInput.equals(""))
        {
            JOptionPane.showMessageDialog(this,"Please Write Password","Password?",ERROR_MESSAGE);
            return;
        }
        
        String passwordFromEagleEyeDataBase = null;
         try
        {
             ee.sql.rs = ee.sql.stmnt.executeQuery( "SELECT * FROM [UserTable] " +
                                                    "WHERE [UserId] = '"+userIdInput+"'");            
             if(!ee.sql.rs.isBeforeFirst())
             {
                  JOptionPane.showMessageDialog(this, "\""+userIdInput+"\" "+" Is Not a Valid User Name.", "UserId Error.",ERROR_MESSAGE);
                  return;
             }
             while(ee.sql.rs.next())
             {
                passwordFromEagleEyeDataBase = ee.sql.rs.getString("Password");
             }
        }
         catch (SQLException ex)
        {
             Logger.getLogger(SighnInPage.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        passwordFromEagleEyeDataBase = passwordFromEagleEyeDataBase.trim();
         
        if(passwordFromEagleEyeDataBase.compareTo(passwordInput) !=0 )
        {
            JOptionPane.showMessageDialog(this,"Incorrect Password For UserId \" "+userIdInput+" \".","Wrong Password!",ERROR_MESSAGE);
            return;
        }
        
        ee.lp.setUser(userIdInput);
        ee.lp.setVisible(true);
        ee.sip.setVisible(false);*/
    }//GEN-LAST:event_signInButtonActionPerformed

    private void backButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backButtonActionPerformed
        ee.fp.setVisible(true);
        ee.sip.setVisible(false);
    }//GEN-LAST:event_backButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SighnInPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SighnInPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SighnInPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SighnInPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new SighnInPage().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel AftabKhalil;
    public javax.swing.JPanel DeviceConnected;
    private javax.swing.JButton backButton;
    private javax.swing.JLabel logoLabel;
    private javax.swing.JPasswordField passwordField;
    private javax.swing.JLabel passwordLabel;
    private javax.swing.JButton signInButton;
    private javax.swing.JPanel signInPageMainPanel;
    private javax.swing.JTextField userIdField;
    private javax.swing.JLabel userIdLabel;
    // End of variables declaration//GEN-END:variables
}
